Repository stellar/freighter-mobile, pull requests merged in 2025-09, with the labels that each got.

#318 Sentry setup and initial calls
  .gitignore
  __tests__/helpers/stellar.test.ts
  android/app/build.gradle
  android/sentry.properties.example
  ios/Podfile.lock
  ios/freighter-mobile.xcodeproj/project.pbxproj
  ios/sentry.properties.example
  jest.setup.js
  metro.config.js
  package.json
  src/components/App.tsx
  src/components/TransactionDetailsBottomSheet.tsx
  src/components/screens/SendScreen/screens/TransactionAmountScreen.tsx
  src/components/screens/SwapScreen/components/SwapTransactionDetailsBottomSheet.tsx
  src/components/screens/SwapScreen/hooks/useSwapTransaction.ts
  src/components/screens/SwapScreen/screens/SwapAmountScreen.tsx
  src/components/screens/SwapScreen/screens/SwapProcessingScreen.tsx
  src/config/logger.ts
  src/config/sentryConfig.ts
  src/ducks/auth.ts
  src/ducks/balances.ts
  src/ducks/sendRecipient.ts
  src/ducks/swap.ts
  src/ducks/transactionBuilder.ts
  src/helpers/browser.ts
  src/helpers/cachedFetch.ts
  src/helpers/encryptPassword.ts
  src/helpers/keyManager/ReactNativeKeychainFacade.ts
  src/helpers/keyManager/ReactNativeKeychainKeyStore.ts
  src/helpers/screenshots.ts
  src/helpers/stellar.ts
  src/helpers/walletKitUtil.ts
  src/hooks/useManageTokens.ts
  src/hooks/useNetworkFees.ts
  src/hooks/useValidateTransactionMemo.ts
  src/hooks/useWalletKitEventsManager.ts
  src/hooks/useWelcomeBanner.ts
  src/services/analytics/core.ts
  src/services/backend.ts
  src/services/friendbot.ts
  src/services/stellar.ts
  src/services/stellarExpert.ts
  src/services/storage/reactNativeKeychainStorage.ts
  src/services/transactionService.ts
  src/types/env.d.ts
  yarn.lock
Labels: enhancement

#325 [Discovery] Add blur to tabs thumbnails
  ios/Podfile.lock
  jest.config.js
  jest.setup.js
  package.json
  src/config/constants.ts
  src/helpers/screenshots.ts
  yarn.lock
Labels: enhancement

#321 QR Code "Send To" Flow
  __tests__/components/screens/SendScreen/SendSearchContacts.test.tsx
  __tests__/helpers/qrValidation.test.ts
  ios/Podfile.lock
  src/components/QRScanner.tsx
  src/components/WalletConnectManualInputOverlay.tsx
  src/components/screens/AccountQRCodeScreen/AccountQRCodeScreen.tsx
  src/components/screens/ScanQRCodeScreen.tsx
  src/components/screens/ScanQRCodeScreen/ScanQRCodeScreen.tsx
  src/components/screens/ScanQRCodeScreen/index.ts
  src/components/screens/SendScreen/SendSearchContacts.tsx
  src/components/screens/SendScreen/screens/TransactionAmountScreen.tsx
  src/config/constants.ts
  src/config/routes.ts
  src/ducks/qrData.ts
  src/helpers/qrValidation.ts
  src/hooks/useHomeHeaders.tsx
  src/hooks/useQRCodeScreenScanner.tsx
  src/hooks/useSendFlowQrCodeScanner.tsx
  src/hooks/useWalletConnectQrCodeScanner.tsx
  src/i18n/locales/en/translations.json
  src/i18n/locales/pt/translations.json
  src/navigators/RootNavigator.tsx
  src/services/analytics/types.ts
Labels: enhancement

#323 Secure Clipboard copy + auto expiration
  __tests__/components/screens/RecoveryPhraseScreen.test.tsx
  __tests__/hooks/useSecureClipboard.test.tsx
  android/app/src/main/java/com/freightermobile/MainApplication.kt
  android/app/src/main/java/org/stellar/freighterwallet/SecureClipboardModule.java
  android/app/src/main/java/org/stellar/freighterwallet/SecureClipboardPackage.java
  ios/Podfile
  ios/Podfile.lock
  ios/SecureClipboard.m
  ios/SecureClipboard.podspec
  ios/SecureClipboard.swift
  ios/freighter-mobile-Bridging-Header.h
  ios/freighter-mobile.xcodeproj/project.pbxproj
  src/components/screens/RecoveryPhraseScreen.tsx
  src/components/screens/SettingsScreen/SecurityScreen/YourRecoveryPhraseScreen/YourRecoveryPhraseScreen.tsx
  src/hooks/useSecureClipboard.ts
  src/services/SecureClipboardService.ts
  src/types/SecureClipboardNative.ts
Labels: enhancement

#333 [FIX] Improve balance Items percentage comparison
  __tests__/components/BalanceRow.test.tsx
  src/components/BalanceRow.tsx
  src/config/constants.ts
Labels: bug

#337 [FIX] Remove unused permissions
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  src/hooks/useDeviceStorage.ts
Labels: bug

#372 [CHORE] Added publicKey tag to sentry
  src/components/App.tsx
  src/config/sentryConfig.ts
  src/hooks/useSentryContext.ts
Labels: enhancement

#379 [CHORE] Add download links to README file
  README.md
Labels: documentation

#342 [FEAT] History list improvements
  __tests__/components/BalancesList.test.tsx
  __tests__/components/SimpleBalancesList.test.tsx
  __tests__/components/screens/HistoryScreen.test.tsx
  __tests__/components/screens/TokenDetailsScreen/TokenDetailsScreen.test.tsx
  __tests__/hooks/useGetHistoryData.test.ts
  src/components/BalancesList.tsx
  src/components/SimpleBalancesList.tsx
  src/components/TransactionDetailsBottomSheet.tsx
  src/components/screens/AddTokenScreen/AddTokenScreen.tsx
  src/components/screens/HistoryScreen/HistoryList.tsx
  src/components/screens/HistoryScreen/HistoryScreen.tsx
  src/components/screens/SendScreen/screens/TransactionAmountScreen.tsx
  src/components/screens/SwapScreen/components/SwapReviewBottomSheet.tsx
  src/components/screens/SwapScreen/components/SwapTransactionDetailsBottomSheet.tsx
  src/components/screens/SwapScreen/hooks/useSwapTransaction.ts
  src/components/screens/SwapScreen/screens/SwapAmountScreen.tsx
  src/components/screens/TokenDetailsScreen/TokenDetailsScreen.tsx
  src/ducks/history.ts
  src/hooks/useBalancesList.ts
  src/hooks/useGetHistoryData.ts
  src/hooks/useHistoryPolling.ts
  src/i18n/locales/en/translations.json
  src/i18n/locales/pt/translations.json
  src/navigators/TabNavigator.tsx
Labels: enhancement
