Repository stellar/freighter-mobile, pull requests merged in 2025-04, with the labels that each got.

#87 Add Trustlines UI
  __tests__/components/BalanceRow.test.tsx
  __tests__/components/BalancesList.test.tsx
  __tests__/components/SimpleBalancesList.test.tsx
  __tests__/components/screens/HomeScreen.test.tsx
  __tests__/components/sds/Avatar.test.tsx
  babel.config.js
  global.css
  ios/Podfile.lock
  ios/freighter-mobile.xcodeproj/project.pbxproj
  jest.config.js
  metro.config.js
  nativewind-env.d.ts
  package.json
  src/components/App.tsx
  src/components/BalanceRow.tsx
  src/components/BalancesList.tsx
  src/components/BottomSheet.tsx
  src/components/ContextMenuButton.tsx
  src/components/CustomNavigationHeader.tsx
  src/components/FriendbotButton.tsx
  src/components/IconButton.tsx
  src/components/SimpleBalancesList.tsx
  src/components/layout/BaseLayout.tsx
  src/components/screens/AddAssetScreen.tsx
  src/components/screens/DiscoveryScreen.tsx
  src/components/screens/HistoryScreen.tsx
  src/components/screens/HomeScreen.tsx
  src/components/screens/LockScreen.tsx
  src/components/screens/ManageAssetsScreen.tsx
  src/components/sds/Avatar/index.tsx
  src/components/sds/Input/index.tsx
  src/config/colors.ts
  src/config/routes.ts
  src/config/theme.ts
  src/config/types.ts
  src/hooks/useBalancesList.ts
  src/hooks/useClipboard.ts
  src/i18n/locales/en/translations.json
  src/i18n/locales/pt/translations.json
  src/index.ts
  src/navigators/ManageAssetsNavigator.tsx
  src/navigators/RootNavigator.tsx
  src/types/nativewind-env.d.ts
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#91 Fix infinity loop on new accounts
  __tests__/components/BalancesList.test.tsx
  src/components/FriendbotButton.tsx
  src/hooks/useBalancesList.ts
Labels: bug

#88 Settings - Sign out
  __tests__/components/List.test.tsx
  __tests__/components/screens/HomeScreen.test.tsx
  __tests__/components/screens/SettingsScreen.test.tsx
  android/app/src/main/res/drawable/baseline_settings_24.xml
  ios/Podfile.lock
  ios/freighter-mobile.xcodeproj/project.pbxproj
  jest.config.js
  package.json
  src/components/BottomSheet.tsx
  src/components/ContextMenuButton.tsx
  src/components/CustomNavigationHeader.tsx
  src/components/List.tsx
  src/components/primitives/Menu.tsx
  src/components/screens/AddAssetScreen.tsx
  src/components/screens/HomeScreen.tsx
  src/components/screens/ManageAssetsScreen.tsx
  src/components/screens/SettingsScreen.tsx
  src/components/sds/Notification/index.tsx
  src/config/routes.ts
  src/config/theme.ts
  src/hooks/useAssetActions.ts
  src/i18n/locales/en/translations.json
  src/i18n/locales/pt/translations.json
  src/navigators/RootNavigator.tsx
  src/navigators/SettingsNavigator.tsx
  src/providers/ToastProvider.tsx
  yarn.lock
Labels: enhancement

#97 Fix spacing inconsistencies across different devices
  ios/freighter-mobile/PrivacyInfo.xcprivacy
  jest.setup.js
  src/components/BottomSheet.tsx
  src/components/CustomNavigationHeader.tsx
  src/components/layout/BaseLayout.tsx
  src/components/layout/OnboardLayout.tsx
  src/components/primitives/Menu.tsx
  src/components/screens/AddAssetScreen/AddAssetBottomSheetContent.tsx
  src/components/screens/AddAssetScreen/AddAssetScreen.tsx
  src/components/screens/LockScreen.tsx
  src/components/screens/WelcomeScreen.tsx
  src/components/sds/Input/index.tsx
  src/helpers/__mocks__/dimensions.ts
  src/helpers/device.ts
  src/helpers/dimensions.ts
Labels: bug

#105 yarn.lock updates
  yarn.lock
Labels: dependencies

#107 Fix White line appearing on BottomSheet handle component
  src/components/BottomSheet.tsx
Labels: bug, enhancement
